### ISSUE TITLE
Support for SSL

### ISSUE THREAD

**Issue by alexreinert** [alexreinert/debmatic#3]

**Comment by Sneeks09** [comment]
Hallo Alex,

sehr gute Arbeit. Was wird für SSL benötigt?
SSL mit Lighttpd sollte kein Problem sein mit eigenem Zertifikat. Soll dies auch über die GUI integriert werden?

Grüße
Sneeks

**Comment by markusmaker** [comment]
Also wenn du ein Script für einen Reverse proxy mit lets encrypt auf Basis haproxy oder nginx brauchst sag Bescheid.

**Comment by s0riak** [comment]
@alexreinert wirklich tolle Arbeit, Danke!

Habe es gerade mit https://github.com/alexreinert/HB-RF-ETH zum Laufen gebracht und damit endlich die virtualisierte Lösung die ich mir gewünscht habe. Wie kann ich debmatic beibringen, dass es nur noch lokal erreichbar ist? Dann kann man, wie von @markusmaker vorgeschlagen, einen reverse-proxy mit SSL davor hängen und hat die Verbindung abgesichert.

Damit im (eignen) Netzwerk alles verschlüsselt ist, müsste natürlich HB-RF-ETH auch noch verschlüsselt mit dem Client und debmatic kommunizieren können, aber eins nach dem anderen. ;)

**Comment by Noschvie** [comment]
@markusmaker : Markus, hast du eine Idee, wie ein Traefik Container konfiguriert werden muss, um "reach an existing Debmatic service on the LAN" zu ermöglichen?
URL der lokalen Debmatic Instanz: `http://192.168.1.75:8010`
baumgarten.<myDomain> ist ein RPi4 mit Traefik und Node-RED. Das Node-RED Dashboard und Traefik funktionieren korrekt.

Anbei die (nicht funktionierende) Traefik Datei:
```
## DYNAMIC CONFIGURATION
# http routing section
http:
  routers:
    # Define a connection between requests and services
    to-local-ip:
      rule: Host(`baumgarten.<myDomain>`) && PathPrefix(`/debmatic/`)
      # If the rule matches, forward to the debmatic service (declared below)
      entryPoints:
        - web
      service: debmatic

  middlewares:
    # Define an authentication mechanism

  services:
    to-local-ip:
      # Define how to reach an existing service on our infrastructure
      loadBalancer:
        servers:
          - url: "http://192.168.1.75:8010"
```
